/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

export default function problem002(n: number) {
  let total: number = 0;
  let fibSeq: [number, number] = [1, 1];

  while (true) {
    let nextNumInFibSeq: number = fibSeq[0] + fibSeq[1];
    
    if (nextNumInFibSeq > n) {
      break;
    }

    if (nextNumInFibSeq % 2 == 0) {
      total += nextNumInFibSeq;
    }

    fibSeq[0] = fibSeq[1];
    fibSeq[1] = nextNumInFibSeq;
  }

  return total;
}